"""
================================================================================
THIS FILE'S JOB IS TO DEFINE DATABASE MODELS (ORM TABLES)
================================================================================

1. Why this file exists:
   In modern software development, we use an Object-Relational Mapper (ORM)
   like SQLAlchemy. Instead of writing raw SQL commands ("CREATE TABLE...",
   "INSERT INTO..."), we define Python classes that represent our database tables.
   This file is the single source of truth for our database table schema.

2. What it does:
   - Defines the `Conversation` model representing the `conversations` table in SQLite.
   - Maps Python attributes (id, user_message, assistant_response, created_at)
     to relational columns with specific data types and constraints.

3. Who communicates with it:
   - `database/connection.py` inspects this model to generate tables via `Base.metadata.create_all()`.
   - `services/conversation_service.py` creates instances of `Conversation` to save
     records or queries them to read history.

4. What it sends to the next layer:
   - Python objects representing database rows (instances of `Conversation`) to the service layer.

5. What it receives back:
   - Input values from the service layer when instantiating new rows.
================================================================================
"""

from datetime import datetime, timezone
from sqlalchemy import Column, Integer, Text, DateTime
from database.connection import Base


class Conversation(Base):
    """
    SQLAlchemy Model representing the 'conversations' table in SQLite.

    Architecture Concept:
        Application Data (Python Object)
                ↓
        Database Model (SQLAlchemy Class)
                ↓
        Database Table (SQLite Relational Table)

    Columns:
        - id: Unique integer identifier for each conversation (Primary Key).
        - user_message: The support question submitted by the user.
        - assistant_response: The answer generated by the bank support service.
        - created_at: Timestamp recorded when the conversation is stored.
    """
    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_message = Column(Text, nullable=False)
    assistant_response = Column(Text, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    def __repr__(self):
        return f"<Conversation(id={self.id}, user_message='{self.user_message[:20]}...', created_at={self.created_at})>"
